"""
llm_explainer.py
Uses Anthropic Claude API ONLY for generating human-readable explanations.
Does NOT use LLM for any decisions — all architecture logic is rule-based.
"""

import os
import json
import httpx
from typing import Any

from .currency import convert_usd_mentions_to_inr, format_inr


ANTHROPIC_API_URL = "https://api.anthropic.com/v1/messages"
MODEL             = "claude-sonnet-4-20250514"


async def generate_explanation(
    features: dict,
    architecture: dict,
    cost: dict,
    failures: list,
    api_key: str,
) -> str:
    """
    Send structured architecture data to Claude and get a human-readable
    explanation. Claude is NOT making decisions here — it is narrating
    decisions already made by the rule-based engines.
    """

    system_prompt = (
        "You are Archon AI's explanation module. You receive structured architecture data "
        "that was generated by a rule-based system. Your job is to write a clear, "
        "professional, 4-6 paragraph explanation of the architecture for a technical evaluator. "
        "Do NOT add new recommendations or change any decisions. Just explain what was decided "
        "and why, in plain English. Be concise and specific. All monetary values must be "
        "expressed in Indian Rupees (INR) using the ₹ symbol and Indian numbering format. "
        "Never output USD, $, dollars, or any other currency unless explicitly requested."
    )

    user_content = f"""
Architecture data to explain:

FEATURES DETECTED:
{json.dumps(features, indent=2)}

ARCHITECTURE DECISION:
- Type: {architecture.get('architecture')}
- Confidence: {architecture.get('confidence')}%
- Reason: {architecture.get('reason')}
- Tradeoffs: {architecture.get('tradeoffs')}

COMPONENT STACK:
{json.dumps(architecture.get('components', []), indent=2)}

COST ESTIMATE (monthly):
- Currency: INR
- Total: {format_inr(cost.get('total_monthly'))}
- Compute: {format_inr(cost.get('compute'))} | DB: {format_inr(cost.get('database'))} | Storage: {format_inr(cost.get('storage'))}

TOP FAILURE RISKS:
{json.dumps(failures[:3], indent=2)}

Write a 4-6 paragraph technical explanation covering: why this architecture was chosen, 
key components and their roles, cost rationale, and top risk mitigations.
"""

    try:
        async with httpx.AsyncClient(timeout=30.0) as client:
            resp = await client.post(
                ANTHROPIC_API_URL,
                headers={
                    "x-api-key":         api_key,
                    "anthropic-version": "2023-06-01",
                    "content-type":      "application/json",
                },
                json={
                    "model":      MODEL,
                    "max_tokens": 800,
                    "system":     system_prompt,
                    "messages":   [{"role": "user", "content": user_content}],
                }
            )
            resp.raise_for_status()
            data = resp.json()
            return convert_usd_mentions_to_inr(data["content"][0]["text"])

    except Exception as e:
        # Fallback: synthesize explanation from structured data without LLM
        return _fallback_explanation(features, architecture, cost, failures)


def _fallback_explanation(features, architecture, cost, failures) -> str:
    arch     = architecture.get("architecture", "")
    reason   = architecture.get("reason", "")
    tradeoff = architecture.get("tradeoffs", "")
    scale    = features.get("scale", 0)
    total    = cost.get("total_monthly", 0)

    parts = [
        f"Archon AI selected a {arch} architecture for this project. {reason}",
        f"The system is designed for {scale:,} concurrent users with "
        f"{'real-time event streaming, ' if features.get('real_time') else ''}"
        f"{'payment processing, ' if features.get('payments') else ''}"
        f"{'AI/ML capabilities, ' if features.get('ai_required') else ''}"
        f"and cloud deployment on AWS.",
        f"Estimated monthly infrastructure cost is {format_inr(total)}, "
        f"covering compute, database, storage, networking, and monitoring.",
        f"Key tradeoff: {tradeoff}",
        f"The top failure risk is: {failures[0]['scenario'] if failures else 'N/A'}. "
        f"Mitigation: {failures[0]['mitigation'] if failures else 'N/A'}",
    ]
    return convert_usd_mentions_to_inr("\n\n".join(parts))
